version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    env_file: ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  ai-ml:
    build: ./ai-ml
    ports:
      - "5001:5001"
